version: "3.9"
services:
  app:
    container_name: urlshortener
    image: mtzimba/urlshortener
    build: .
    links:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - ~/docker/redis:/redis-service/logs
  redis:
    container_name: redis
    image: redis:lastet
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"